# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18xEH-K66eEBXWP_2kbM2WilR9eJG9YAL
"""

# Función para calcular la edad en años dado una fecha de nacimiento y la fecha actual
from datetime import datetime

def calcular_edad(fecha_nacimiento):
    fecha_actual = datetime.now()
    edad = fecha_actual.year - fecha_nacimiento.year - ((fecha_actual.month, fecha_actual.day) < (fecha_nacimiento.month, fecha_nacimiento.day))
    return edad

# Lista de oficios deseados
oficios_deseados = ["ingeniero", "enfermero", "profesor", "programador", "electricista", "mecánico", "chef", "plomero", "agricultor", "arquitecto"]

# Función para obtener los datos de un progenitor
def obtener_datos_progenitor(numero):
    print(f"Ingrese los datos del progenitor {numero}:")
    sexo = input("Sexo (M: Masculino; F: Femenino; N: No binario): ").upper()
    fecha_nacimiento = datetime.strptime(input("Fecha de nacimiento (YYYY-MM-DD): "), "%Y-%m-%d")
    grado_academico = input("Grado académico (P: Postgraduado; U: Universitario; T: Técnico; N: Ninguno): ").upper()
    tiene_oficio = input("¿Tiene alguno de los 10 oficios requeridos? (S/N): ").upper() == "S"

    edad = calcular_edad(fecha_nacimiento)
    puntos = 0

    # Calcular puntos por edad fértil y sexo femenino
    if sexo == "F":
        edad_fertil = max(0, min(edad - 20, 35 - 20))
        puntos += edad_fertil

    # Calcular puntos adicionales por grado académico y oficio
    if grado_academico == "P":
        puntos += 5
    elif grado_academico == "U":
        puntos += 3

    if tiene_oficio and any(oficio.lower() in oficios_deseados for oficio in input("Ingrese los oficios separados por comas: ").split(',')):
        puntos += 8

    puntos += 6  # Sumar puntos base por progenitor
    return puntos

# Función para obtener los datos de los hijos
def obtener_datos_hijos():
    cantidad_hijos = int(input("Ingrese la cantidad de hijos: "))
    puntos_totales_hijos = 0

    for i in range(cantidad_hijos):
        print(f"Ingrese los datos del hijo {i + 1}:")
        sexo_hijo = input("Sexo (M: Masculino; F: Femenino; N: No binario): ").upper()
        fecha_nacimiento_hijo = datetime.strptime(input("Fecha de nacimiento del hijo (YYYY-MM-DD): "), "%Y-%m-%d")
        edad_hijo = calcular_edad(fecha_nacimiento_hijo)
        puntos_totales_hijos += 8

    return puntos_totales_hijos

# Obtener datos de la familia
print("Bienvenido al formulario de calificación de familias para residencia en Australia.")
tipo_familia = input("¿La familia es monoparental (MP) o biparental (BP)? ").upper()

puntos_totales = 0

# Obtener datos de progenitores y sumar puntos
if tipo_familia == "MP":
    puntos_totales += obtener_datos_progenitor(1)
else:
    puntos_totales += obtener_datos_progenitor(1)
    puntos_totales += obtener_datos_progenitor(2)

# Obtener datos de los hijos y sumar puntos
puntos_totales += obtener_datos_hijos()

print(f"El puntaje total de la familia es: {puntos_totales}")